const lessons = [
    {
      id: 1,
      subject: 'Math',
      location: 'Room A',
      price: 20,
      spaces: 5,
      icon: 'fa-calculator', 
    },
    {
      id: 2,
      subject: 'Science',
      location: 'Lab B',
      price: 25,
      spaces: 5,
      icon: 'fa-flask', 
    },
    {
      id: 3,
      subject: 'History',
      location: 'Room C',
      price: 15,
      spaces: 5,
      icon: 'fa-book', 
    },
    {
      id: 4,
      subject: 'Literature',
      location: 'Room D',
      price: 18,
      spaces: 5,
      icon: 'fa-book-open', 
    },
    {
      id: 5,
      subject: 'Art',
      location: 'Studio A',
      price: 30,
      spaces: 5,
      icon: 'fa-paint-brush',
    },
    {
      id: 6,
      subject: 'Music',
      location: 'Studio B',
      price: 22,
      spaces: 5,
      icon: 'fa-music', 
    },
    {
      id: 7,
      subject: 'Physical Education',
      location: 'Field',
      price: 17,
      spaces: 5,
      icon: 'fa-running', 
    },
    {
      id: 8,
      subject: 'Computer Science',
      location: 'Lab C',
      price: 28,
      spaces: 5,
      icon: 'fa-laptop-code', 
    },
    {
      id: 9,
      subject: 'Biology',
      location: 'Lab D',
      price: 26,
      spaces: 5,
      icon: 'fa-microscope', 
    },
    {
      id: 10,
      subject: 'Film',
      location: 'Theare A',
      price: 45,
      spaces: 5,
      icon: 'fa-film', 
    },
  ];
  
 
  